const JERSEYS = {
  1: {
    id: 1,
    name: "De Toekomst Legacy",
    club: "AFC Ajax",
    era: "Historic European Triumphs × 2019 UEFA Champions League Run",
    eraKey: "1990s",
    primaryColor: "Red",
    competition: "UEFA Champions League",
    image: "Ajax.png",
    colors: ["Red", "White", "Black"],
    description: "This custom Ajax jersey blends the club’s iconic home identity with references to both its historic European dominance and the unforgettable 2019 UEFA Champions League run. The bold central red panel reflects Ajax’s timeless home kit design, while the clean white sleeves preserve the club’s traditional visual balance. Minimalist detailing and modern fabric construction introduce a contemporary edge, ensuring the jersey feels relevant to the 2025 era. Subtle Champions League elements and refined sponsor placement maintain a clean aesthetic that allows the club crest and overall structure to remain the focal points.",
    heritage: "Inspired by Ajax’s legacy as one of Europe’s most influential clubs, this jersey pays tribute to multiple eras of success — from European Cup triumphs led by Dutch legends such as Marco van Basten, Ruud Gullit, and Frank Rijkaard, to the fearless 2019 Champions League campaign that reignited the club’s attacking philosophy on the European stage. The design reflects continuity, youth, and tactical intelligence across generations.",
    badge: "Classic Ajax crest symbolizing the club’s enduring European identity"

  },
  2: {
    id: 2,
    name: "Invincible Legacy",
    club: "Arsenal FC",
    era: "2004 Invincibles × 2024 Modern Era",
    eraKey: "2000s",
    primaryColor: "Red",
    competition: "Premier League",
    image: "Arsenal.png",
    colors: ["Red", "White", "Gold", "Yellow"],
    description: "This custom jersey reinterprets Arsenal’s legendary 2003–04 Invincibles kit through a modern 2024 design lens. The dominant red body pays tribute to the iconic home shirts worn during the unbeaten league season, symbolising dominance and identity, while the white side panels reference traditional Arsenal sleeve designs from the early 2000s. A modern slim-fit silhouette and clean typography reflect Arsenal’s contemporary 2024 aesthetic, ensuring the jersey feels current and wearable for younger fans. Subtle gold detailing is used to signify excellence and the historic achievement of an unbeaten league campaign, blending nostalgia with modern minimalism without directly replicating any original kit.",
    heritage: "Inspired by Arsenal’s 2003–04 Invincibles season, when the club completed an entire Premier League campaign unbeaten, this jersey celebrates one of the most iconic achievements in English football history. The design preserves Arsenal’s cultural identity through its classic red-and-white palette while modernising the layout to reflect the club’s present-day evolution and renewed competitive ambition in the 2024 season.",
    badge: "Modernised Arsenal crest inspired by the club’s historic cannon emblem"
  },
  3: {
    id: 3,
    name: "Blaugrana Unity",
    club: "FC Barcelona",
    era: "2009 Champions League × 2025 Modern Era",
    eraKey: "2000s",
    primaryColor: "Blue",
    competition: "UEFA Champions League",
    image: "Barcelona.png",
    colors: ["Blue", "Red", "Yellow"],
    description: "This custom FC Barcelona jersey blends the historic 2009 UEFA Champions League-winning identity with a modern 2025 design approach. The classic vertical Blaugrana stripes reference the iconic kit worn during Barcelona’s treble-winning season, while the refined stripe spacing and modern V-neck collar reflect contemporary football aesthetics. The inclusion of a UNICEF reference pays tribute to Barcelona’s commitment to social responsibility, echoing the values represented on the 2009 shirt. Modern sponsor typography and clean detailing ensure visual clarity and relevance for younger audiences, while the UEFA Champions League badge reinforces the club’s European legacy.",
    heritage: "Inspired by FC Barcelona’s legendary 2009 season, this jersey celebrates a defining moment in the club’s history when success, identity, and values aligned on the European stage. By combining the symbolic elements of the 2009 kit with a modern 2025 structure, the design preserves emotional and cultural significance for long-time supporters while presenting a refreshed and accessible interpretation for a new generation of fans.",
    badge: "Modern FC Barcelona crest inspired by the historic club badge used during European triumphs"

  },
  4: {
    id: 4,
    name: "O Número 10 Eterno",
    club: "Brazil National Team",
    era: "2002 FIFA World Cup × 2014 Neymar Era",
    eraKey: "2000s",
    primaryColor: "Canary Yellow",
    competition: "FIFA World Cup",
    image: "Brazil.png",
    colors: ["Yellow", "Green", "Blue"],
    description: "This Brazil jersey fuses the iconic 2002 World Cup-winning design with modern elements inspired by the 2014 tournament era. The classic canary yellow base dominates the shirt, complemented by deep green side panels and sleeve accents that add a contemporary silhouette. A modern V-neck collar introduces a streamlined 2025 aesthetic while maintaining Brazil’s traditional color balance. The centrally placed number 10 stands as the visual anchor, reinforcing the jersey’s symbolic importance and ensuring the design remains bold, clean, and instantly recognizable.",
    heritage: "Rooted in Brazil’s fifth World Cup triumph in 2002, this jersey honors the fluid, joyful football that defined the Seleção’s golden generation. It also pays tribute to the 2014 era, led by Neymar, who carried the iconic number 10 and the weight of national expectation on home soil. By blending these two moments, the jersey represents continuity between past brilliance and modern expression, celebrating Brazil’s enduring attacking identity and global influence.",
    badge: "CBF crest with championship stars symbolizing Brazil’s World Cup legacy"
  },
  5: {
    id: 5,
    name: "Golden European Resolve",
    club: "Chelsea FC",
    era: "2017 Yellow Away × 2021 Champions League",
    eraKey: "2010s",
    primaryColor: "Yellow",
    competition: "UEFA Champions League",
    image: "chelsea_jersey.png",
    colors: ["Yellow", "White", "Black"],
    description: "This custom Chelsea FC jersey merges the bold visual identity of the club’s 2017 yellow away kit with the modern design language of the 2021 UEFA Champions League-winning season. The striking yellow base draws direct inspiration from the 2017 jersey, symbolising confidence and individuality, while the horizontal banding and clean panel structure reflect contemporary football aesthetics. Modern sponsor placement and simplified typography ensure clarity and balance, while subtle graphic textures add depth without overpowering the design. The inclusion of Champions League elements reinforces Chelsea’s recent European success, creating a strong visual connection between past style and modern achievement.",
    heritage: "Inspired by Chelsea’s evolution from a distinctive Premier League contender to European champions in 2021, this jersey represents resilience, adaptability, and growth. By combining the iconic yellow identity from 2017 with references to the club’s Champions League triumph, the design preserves emotional familiarity for long-time supporters while presenting a refreshed and meaningful interpretation for younger fans.",
    badge: "Modern Chelsea FC crest inspired by the club’s historic lion emblem and European success"

  },
  6: {
    id: 6,
    name: "Sky Blue Heritage",
    club: "Manchester City FC",
    era: "Classic Club Identity × Modern Puma Era",
    eraKey: "1990s",
    primaryColor: "Sky Blue",
    competition: "Domestic League",
    image: "Manchester City.png",
    colors: ["Sky Blue", "White", "Gold"],
    description: "This custom Manchester City jersey reinterprets the club’s retro identity by combining a traditional sky-blue base with modern design elements associated with the Puma era. The clean sky-blue colour pays tribute to City’s historic home kits, while the curved white side panels reference older shirt constructions from earlier decades. The use of the classic club badge reinforces the jersey’s connection to Manchester City’s heritage, while modern sponsor placement and streamlined typography ensure visual clarity and relevance. A refined V-neck collar and minimal detailing give the jersey a contemporary finish without compromising its traditional character.",
    heritage: "Inspired by Manchester City’s historical club identity prior to its modern dominance, this jersey celebrates the evolution of the club while preserving its original visual essence. By blending the retro badge with modern Puma-era styling, the design creates a meaningful connection between City’s past and present, appealing to long-time supporters and a new generation of fans.",
    badge: "Classic Manchester City crest inspired by the club’s earlier badge designs"
  },
  7: {
    id: 7,
    name: "Rossoneri European Legacy",
    club: "AC Milan",
    era: "2007 Champions League × Modern Era",
    eraKey: "2000s",
    primaryColor: "Red",
    competition: "UEFA Champions League",
    image: "Milan.png",
    colors: ["Red", "Black", "Gold", "White"],
    description: "This custom AC Milan jersey draws inspiration from the club’s iconic 2007 UEFA Champions League triumph, combining its historic European identity with a contemporary design approach. The classic red and black vertical stripes reflect Milan’s timeless Rossoneri heritage, while the updated stripe proportions and streamlined silhouette align with modern football jersey aesthetics. Historic sponsor typography inspired by the 2007 Champions League-winning kit reinforces the jersey’s nostalgic connection, while modern fabric structuring and clean detailing ensure the design feels current. Subtle gold accents are incorporated to symbolise European success and prestige without overpowering the traditional colour scheme.",
    heritage: "Inspired by AC Milan’s 2007 UEFA Champions League victory, this jersey pays tribute to one of the club’s most successful European eras. The design reflects Milan’s dominance on the continental stage while preserving its traditional red-and-black identity, blending historical significance with a modern reinterpretation that appeals to both long-time supporters and younger fans.",
    badge: "Modernised AC Milan crest inspired by the historic oval badge used during the club’s European triumphs"
  },
  8: {
    id: 8,
    name: "Dragões 2004 Reimagined",
    club: "FC Porto",
    era: "2004 UEFA Champions League Triumph × 2025 Modern Design",
    eraKey: "2000s",
    primaryColor: "White",
    competition: "UEFA Champions League",
    image: "Porto.png",
    colors: ["White", "Royal Blue", "Light Blue"],
    description: "This custom FC Porto jersey fuses the club’s iconic 2004 UEFA Champions League-winning identity with a contemporary 2025 design approach. The classic white base and central blue vertical stripe pay direct homage to Porto’s traditional European kits, while the fractured, marble-like graphic pattern introduces a modern, dynamic texture that symbolizes resilience and intensity. The updated V-neck collar and streamlined sleeve construction reflect modern performance-focused aesthetics, while the sponsor and badge placement remain clean and balanced to preserve visual clarity. A Champions League sleeve badge reinforces the jersey’s strong European legacy.",
    heritage: "Inspired by FC Porto’s legendary 2003–04 Champions League campaign, this jersey celebrates one of the most iconic underdog triumphs in modern football history. By blending traditional club colours and structure with modern textures and 2025 styling, the design bridges Porto’s historic European dominance with its evolving modern identity.",
    badge: "Classic FC Porto crest representing the club’s historic European success"
  },
};
